"""add operator model

Revision ID: 683119e46a90
Revises: 7afcd3899c9e
Create Date: 2025-10-23 18:28:12.339026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683119e46a90'
down_revision: Union[str, Sequence[str], None] = '7afcd3899c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_operators_id'), 'operators', ['id'], unique=False)
    op.drop_constraint(op.f('buses_operator_id_fkey'), 'buses', type_='foreignkey')
    op.create_foreign_key(None, 'buses', 'operators', ['operator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.create_foreign_key(op.f('buses_operator_id_fkey'), 'buses', 'users', ['operator_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_operators_id'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
